stages:
  - rpm-package
  - local-test
  - e2e-distributed
  - rpm-stable

rpm-package:
  stage: rpm-package
  script:
    - 'rpm-package.sh'
  except:
    - master

unit-test:
  stage: local-test
  script:
    - 'unit-test.sh'
  except:
    - master

unit-test-python27:
  stage: local-test
  tags:
    - docker
  script:
    - 'unit-test-virtualenv.sh'
  allow_failure: true
  except:
    - master

unit-test-python36:
  stage: local-test
  tags:
    - docker
  script:
    - 'unit-test-virtualenv.sh python36'
  allow_failure: true
  except:
    - master

e2e-localhost-preservation:
  stage: local-test
  script:
    - 'e2e-localhost.sh preservation'
  except:
    - master

e2e-localhost-access-rest-api:
  stage: local-test
  script:
    - 'e2e-localhost.sh access-rest-api'
  except:
    - master

e2e-distributed-preservation:
  stage: e2e-distributed
  tags:
    - e2e-distributed
  script:
    - 'e2e-distributed.sh preservation'
  after_script:
    - 'sudo umount e2e-distributed-preservation/.sshfs'
  only:
    - develop
    - tags

rpm-stable:
  stage: rpm-stable
  script:
    - 'rpm-stable.sh'
  only:
    - tags
